export const AUTHENTICATE_REQUEST = "AUTHENTICATE_REQUEST";
export const AUTHENTICATE_SUCCESS = "AUTHENTICATE_SUCCESS";
export const AUTHENTICATE_FAIL = "AUTHENTICATE_FAIL";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const LOGOUT = "LOGOUT";
export const PUT_ERROR = "PUT_ERROR";
export const REMOVE_ERRORS = "REMOVE_ERRORS";
export const ADD_SHOP_ITEM = "ADD_SHOP_ITEM";
